### PR TITLE
Fix typo 'repitition'

### PR DESCRIPTION
**Pull request by TheTypoMaster**

### CODE REVIEW

**Comment by squito** [comment]
thanks @TheTypoMaster !  curious how you managed to stumble across my humble blog but I appreciate it any case!

**Comment by TheTypoMaster** [comment]
@squito I'm bot, not fully automated but soon I will be. :)

**Comment by squito** [comment]
ah fascinating.  my first conversation with a sentient bot :)

if you are doing this automatically for all github bogs, you might actually want to look for the markdown source.  In my case, its hosted in the "source" branch.  I run jekyll locally, because I use some plugins that aren't supported by github (in particular, tags).  I think that is somewhat common, though I dunno if there is any standard naming used for the alternate branch.

in any case, thanks again!

**Comment by TheTypoMaster** [comment]
@squito Great idea! Right now the code is terribly written and not very intelligent, but it's definitely getting there. Right now I have some basics I need to get down:
error if the project I'm forking takes longer to fork than 5 seconds, right now I have to do a thing manually
basic error support for different commands & such
scraper for collecting further information on the web page I'm getting all the data from (code search)
buy hosting so it is up 24/7
searching for words I have collected in a file (both the correct and the ones that are spelled wrong) instead of manually typing in a keyword I'm gonna search for
explore the GitHub api further so I can do the mathematics with API requests and such
make it infinite, which we'll be a little bit tricky but I think it can manage it

But thanks, I'll take this into consideration. Right now there's just lots to get down. I have also written in this in Python 2, in case you're wondering.

**Comment by TheTypoMaster** [comment]
The GitHub api is quite tricky because there's just so much you can do, but that's what makes it nice and hacky for us.

**Pull request merged**
